---
alwaysEmailList: ljohnson@dettonville.org
logLevel: DEBUG
maxRandomDelaySeconds: 20
failFast: true

runGroupsInParallel: false
runInParallel: true

buildArgs:
  IMAGE_REGISTRY: media.johnson.int:5000

buildPlatforms:
  - linux/amd64
  - linux/arm64

buildTags:
  - "latest"

buildImageGroups:
  docker-utilities:
    buildImageList:
      - buildImageName: "nord-key-extractor"
        buildDir: "image/nord-key-extractor"
      - buildImageName: "langgraph-router"
        buildDir: "image/langgraph-router"
      - buildImageName: "crewai-workers"
        buildDir: "image/crewai-workers"
